name: Build New Image Version
on:
  # Manually call
  workflow_dispatch:
    inputs:
      release-type:
        required: true
        type: choice
        description: Type of release
        options:
          - patch
          - minor
          - major
      base-version:
        required: true
        description: Base version=
  # Call from other workflow
  workflow_call:
    inputs:
      release-type:
        type: string
        required: true
      base-version:
        type: string
        required: true
defaults:
  run:
    shell: bash -l {0}
jobs:
  open-pr:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    outputs:
      pr_id: ${{ steps.open_pr.outputs.pr_id }}
      target_version: ${{ steps.calc_target.outputs.target_version }}
    steps:
      - uses: actions/checkout@v4
      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: ./environment.yml
          environment-name: sagemaker-distribution
          init-shell: bash
      - name: Free up disk space
        run: rm -rf /opt/hostedtoolcache
      - name: Activate sagemaker-distribution
        run: micromamba activate sagemaker-distribution
      - name: Calculate target version
        id: calc_target
        run: |
          TARGET_VERSION=$(python -c 'import semver; ver=semver.bump_${{ github.event.inputs.release-type }}("1.2.0"); ${{ github.event.inputs.base-version }}')
          echo "target_version=$TARGET_VERSION" >> $GITHUB_OUTPUT
      - name: Create new branch
        run: git checkout -b release-${{github.event.inputs.target-version}}
      - name: Generate artifacts
        run: python ./src/main.py create-${{ github.event.inputs.release-type }}-version-artifacts --base-patch-version ${{ github.event.inputs.base-version }}
      - name: Commit .in artifacts to branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add ./build_artifacts
          git commit -m 'chore: Generate build artifacts for ${{ steps.calc_target.outputs.target_version }} release'
          git push --set-upstream origin release-${{ steps.calc_target.outputs.target_version }}
      - name: Open pull request
        id: open_pr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          URL=$(gh pr create -H release-${{ steps.calc_target.outputs.target_version }} \
                    --title 'release: v${{ steps.calc_target.outputs.target_version }}' --body 'Created by GitHub Action')
          PR=$(echo $URL | sed 's:.*/::')
          echo "pr_id=$PR" >> $GITHUB_OUTPUT
  call-codebuild-project:
    runs-on: ubuntu-latest
    if: github.repository == 'claytonparnell/sagemaker-distribution-test'
    permissions:
      pull-requests: write
      contents: write
      id-token: write
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::428449107377:role/SMDistroUnitTestingRole
          aws-region: us-west-2
      - name: Run CodeBuild
        uses: dark-mechanicum/aws-codebuild@v1
        env:
          CODEBUILD__sourceVersion: 'pr/${{needs.open-pr.outputs.pr_id}}'
        with:
          projectName: cosmos-unit-testing
          buildspec: '{
              "environmentVariablesOverride":[
                { "name":"PR_ID", "value":${{needs.open-pr.outputs.pr_id}}, "type": "PLAINTEXT" },
                { "name":"TARGET_VERSION", "value":"${{needs.open-pr.outputs.target_version}}", "type": "PLAINTEXT" },
                { "name":"RELEASE_TYPE", "value":"${{needs.open-pr.outputs.pr_id}}", "type": "PLAINTEXT" },
              ],
            }'