name: Generate weekly patch release(s)
on:
  # Run every Monday at 8AM PST / 9AM PDT
  schedule:
    - cron: '0 16 * * MON'
  # Manually call (temporary)
  workflow_dispatch:
jobs:
  generate-version-matrix:
    name: Generate-matrix
    runs-on: ubuntu-latest
    if: github.repository == 'claytonparnell/sagemaker-distribution-test'
    outputs:
      matrix: ${{ steps.gen-mat.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - name: Generate patch version matrix
        id: gen-mat
        run: |
          versions=("{\"version\":[")
          for minor in build_artifacts/v*/*; do
            minor_version="${minor##*/}"
            highest_patch=$(ls $minor | sort -t. -k3,3n | tail -n1)
            versions+="\"${highest_patch#v}\""
            versions+=","
          done
          versions=${versions::-1}
          versions+="]}"
          echo "matrix=$versions" >> $GITHUB_OUTPUT

  start-weekly-patch:
    name: Start weekly patch release
    needs: generate-version-matrix
    permissions:
      pull-requests: write
      contents: write
      id-token: write
    strategy:
      matrix: ${{ fromJson(needs.generate-version-matrix.outputs.matrix) }}
    uses: claytonparnell/sagemaker-distribution-test/.github/workflows/build-image.yml@main
    with:
      release-type: "patch"
      base-version: ${{ matrix.version }}